version: '3'

services:
  dev: &dev
    build: .
    working_dir: /code
    command: /bin/bash
    volumes:
     - .:/code
    links:
      - database
  run:
    <<: *dev
    command: php run.php
  change:
    <<: *dev
    command: php change.php
  database:
    image: mysql:5.7
    tty: true
    stdin_open: true
    volumes:
      - ./data/:/var/lib/mysql/
      - ./init/:/docker-entrypoint-initdb.d/
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tm
      - MYSQL_USER=tm
      - MYSQL_PASSWORD=tm
      - LANG=en_US.UTF-8
    entrypoint: 
      - "docker-entrypoint.sh"
      - "--character-set-server=utf8"
      - "--collation-server=utf8_general_ci"
