version: '2'

services:
  database: 
    image: mysql:5.7
    tty: true
    stdin_open: true
    network_mode: bridge
    volumes:
      - ./data/:/var/lib/mysql/
      - ./init/:/docker-entrypoint-initdb.d/
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tm
      - MYSQL_USER=tm
      - MYSQL_PASSWORD=tm
      - LANG=en_US.UTF-8
    entrypoint: 
      - "docker-entrypoint.sh"
      - "--character-set-server=utf8"
      - "--collation-server=utf8_general_ci"
